export const INGREDIENTS: string[] = [
  'Ail', 'Ail pelé', 'Ail semoule', 'Aneth', 'Aubergine', 'Avocat',
  'Basilic', 'Beurre', 'Beurre de lidl', 'Beurre demi sel', 'Beurre salé de lidl',
  'Bœuf', 'Canelle de metro', 'Capres', 'Carotte', 'Champignon de paris',
  'Chou rouge', 'Ciboulette', 'Citron jaune', 'Comté', 'Concentreé tomate',
  'Concentré tomate', 'Concombre', 'Coriandre', 'Courgette', 'Crème 18%',
  'Cumin de metro', 'Curry de metro', 'Eau', 'Echalotte',
  'Epices curry', 'Epices guaca de metro', 'Gingembre de metro', 'Harissa',
  'Huile', 'Huile olive', "Jaune d'œuf", 'Jus de veau', 'Ketchup',
  'Lait entier', 'Laurier', 'Moutarde', "Moutarde à l'ancienne",
  'Muscade de metro', 'Oignon jaune', 'Oignon rouge',
  'Olives', 'Paprika de metro', 'Paprika fumée metro', 'Parmesan', 'Pdt',
  'Persil', 'Pignon', 'Poivre', 'Poivron rouge', 'Polenta', 'Porc',
  'Potimarron', 'Poulet', 'Raclette', 'Romarin', 'Sauce tomate',
  'Saucisse fumée', 'Sucre', 'Sucre blanc', 'Thon', 'Thym', 'Tomate',
  'Vanille liquide', 'Vin', 'Vinaigre blanc', 'Yahourt grec',
  'Epices roti de metro', 'Epices roti lidl', 'Œuf', 'Ketchup', 'Mayo',
  'Prépa aioli', 'Prépa bourguignon', 'Prépa caramel beurre salé', 'Prépa coleslaw',
  'Prépa crème de champi', 'Prépa croissant perdu', 'Prépa guaca',
  'Prépa mayonnaise', 'Prépa mayonnaise harissa', "Prépa mayonnaise moutarde à l'ancienne",
  'Prépa pickles concombre', 'Prépa pickles oignon', 'Prépa pesto', 'Prépa polenta',
  'Prépa polpette', 'Prépa poulet basquaise', 'Prépa puled pork', 'Prépa raclette',
  'Prépa ratatouille', 'Prépa rougail', 'Prépa thon', 'Prépa tzatziki', 'Prépa velouté',
].sort();