export const INGREDIENTS: string[] = [
  'Ail', 'Ail pelé', 'Ail semoule', 'Aneth', 'Aperol', 'Armagnac',
  'Aubergine', 'Avocat', 'Baileys', 'Basilic', 'Beurre', 'Beurre de lidl',
  'Beurre demi sel', 'Beurre salé de lidl', 'Bœuf', 'Burrata', 'Cachaca',
  'Café', 'Café déca', 'Calva', 'Camembert', 'Canard', 'Canelle de metro',
  'Canneberge', 'Capres', 'Carotte', 'Champignon de paris', 'Chantilly',
  'Cheddar', 'Chèvre', 'Chicorée', 'Chocolat', 'Chou rouge', 'Ciboulette',
  'Cidre', 'Citron', 'Citron jaune', 'Cognac', 'Comté', 'Concentreé tomate',
  'Concentré tomate', 'Concombre', 'Coppa', 'Coriandre', 'Courgette',
  'Crème 12%', 'Crème 18%', 'Crème 30%', 'Crème 35%', 'Croissant',
  'Cumin de metro', 'Cumin metro', 'Curry de metro', 'Dinde', 'Eau',
  'Eau gazeuse', 'Echalotte', 'Emmental', 'Epices curry',
  'Epices guaca de metro', 'Epices roti de metro', 'Epices roti lidl',
  'Epinards', 'Farine', 'Fleur d\'oranger', 'Frizzante', 'Get 27', 'Get 31',
  'Gin', 'Gingembre', 'Gingembre de metro', 'Ginger beer', 'Harissa',
  'Huile', 'Huile olive', 'IPA', 'Jambon blanc', 'Jambon cru',
  'Jaune d\'œuf', 'Jus de veau', 'Ketchup', 'Lait', 'Lait entier',
  'Lait végétal', 'Laurier', 'Limonade', 'Limoncello', 'Martini blanc',
  'Martini rouge', 'Matcha', 'Mayo', 'Menthe', 'Mesclun', 'Miel',
  'Mozzarella', 'Moutarde', 'Moutarde à l\'ancienne', 'Muscade de metro',
  'Myrtille', 'Noisette', 'Noix', 'Nutella', 'Œuf', 'Oignon jaune',
  'Oignon rouge', 'Olives', 'Orange', 'Ouzo', 'Paprika de metro',
  'Paprika fumée metro', 'Parmesan', 'Pastrami', 'Pastis', 'Pdt', 'Perrier',
  'Persil', 'Picon', 'Pignon', 'Poivre', 'Poivron rouge', 'Polenta',
  'Pomme', 'Porc', 'Portobello', 'Potimarron', 'Poudre amande', 'Poudre chai',
  'Poulet', 'Praliné', 'Raclette', 'Rhum', 'Riz', 'Romarin',
  'Roti de bœuf', 'Sauce tomate', 'Saucisse fumée', 'Saumon', 'Sirop',
  'Sirop citrouille', 'Sirop de sucre de canne', 'Sirop de violette',
  'Speculoos', 'St ger', 'Steak boeuf', 'Sucre', 'Sucre blanc',
  'Sucre cassonade', 'Sucre de canne', 'Suze', 'Thé', 'Thon', 'Thym',
  'Tomate', 'Tomate cerise', 'Tonic', 'Vanille liquide', 'Vin', 'Vin blanc',
  'Vinaigre blanc', 'Vodka', 'Whisky', 'Yahourt grec',
  'Aioli', 'Bourguignon', 'Caramel beurre salé', 'Coleslaw',
  'Crème de champi', 'Croissant perdu', 'Guaca', 'Mayonnaise',
  'Mayonnaise harissa', 'Mayonnaise moutarde à l\'ancienne',
  'Pickles concombre', 'Pickles oignon', 'Pesto', 'Polpette',
  'Poulet basquaise', 'Puled pork', 'Ratatouille', 'Rougail',
  'Thon prépa', 'Tzatziki', 'Velouté',
].sort();