export const INGREDIENTS: string[] = [
  'Ail', 'Ail semoule', 'Alex', 'Aneth', 'Aperol', 'Armagnac',
  'Aubergine', 'Avocat', 'Baileys', 'Basilic', 'Beurre',
  'Beurre salé', 'Bière du moment', 'Bière sans alcool', 'Blanche', 'Butternut', 'Bœuf', 'Burrata', 'Cachaca',
  'Café', 'Café déca', 'Calva', 'Camembert', 'Canard', 'Canelle de metro',
  'Canneberge', 'Capres', 'Carotte', 'Champignon de paris', 'Chantilly',
  'Cheddar', 'Chèvre', 'Chicorée', 'Chocolat', 'Chou rouge', 'Ciboulette',
  'Cidre', 'Citron jaune', 'Citron vert', 'Cognac', 'Comté', 'Concentré tomate', 'Concombre', 'Coppa', 'Coriandre', 'Corona', 'Courgette',
  'Crème 12%', 'Crème 18%', 'Crème 30%', 'Crème 35%', 'Croissant',
  'Cumin', 'Curry', 'Dinde', 'Eau',
  'Eau gazeuse', 'Echalotte', 'Emmental',
  'Épices rôti',
  'Epinards', 'Farine', 'Fleur d\'oranger', 'Frizzante', 'Get 27', 'Get 31',
  'Gin', 'Gingembre', 'Ginger beer', 'Harissa',
  'Huile', 'Huile olive', 'IPA', 'Jambon blanc', 'Jambon cru',
  'Jaune d\'œuf', 'Jus de veau', 'Ketchup', 'Lait',
  'Lait végétal', 'Laurier', 'Limonade', 'Limoncello', 'Martini blanc',
  'Martini rouge', 'Matcha', 'Menthe', 'Mesclun', 'Miel',
  'Mozzarella', 'Moutarde', 'Moutarde à l\'ancienne', 'Muscade de metro',
  'Myrtille', 'Noisette', 'Noix', 'Nutella', 'Œuf', 'Oignon jaune',
  'Oignon rouge', 'Olives', 'Orange', 'Ouzo', 'Paprika de metro',
  'Panais', 'Paprika fumée metro', 'Parmesan', 'Pastrami', 'Pastis', 'Patate douce', 'Pdt', 'Perrier 1L', 'Perrier 33cl',
  'Persil', 'Picon', 'Pignon', 'Poivre', 'Poivron rouge', 'Polenta',
  'Pomme', 'Porc', 'Portobello', 'Potimarron', 'Poudre amande', 'Poudre chai',
  'Poulet', 'Praliné', 'Raclette', 'Rhum cocktail', 'Rhum digestif', 'Riz', 'Romarin',
  'Roti de bœuf', 'Sauce tomate', 'Saucisse fumée', 'Saumon', 'Sirop',
  'Sirop citrouille', 'Sirop de sucre de canne', 'Sirop de violette',
  'Speculoos', 'St ger', 'Steak boeuf', 'Sucre', 'Sucre blanc',
  'Sucre cassonade', 'Sucre de canne', 'Suze', 'Thé', 'Thon', 'Thym',
  'Tomate', 'Tomate cerise', 'Tomme fraîche', 'Tonic', 'Triple', 'Vanille liquide',
  'Vin blanc', 'Vin rosé', 'Vin rouge', 'Vin rouge cubi',
  'Vinaigre blanc', 'Vodka', 'Whisky', 'Yahourt grec',
].sort();

export const PREPARATIONS: string[] = [
  'Prépa aioli', 'Prépa bourguignon', 'Prépa caramel beurre salé', 'Prépa coleslaw',
  'Prépa crème de champi', 'Prépa croissant perdu', 'Prépa guaca', 'Prépa mayonnaise',
  'Prépa mayonnaise harissa', 'Prépa mayonnaise moutarde à l\'ancienne',
  'Prépa pickles concombre', 'Prépa pickles oignon', 'Prépa pesto', 'Prépa polpette',
  'Prépa poulet basquaise', 'Prépa puled pork', 'Prépa ratatouille été', 'Prépa ratatouille hiver', 'Prépa rougail',
  'Prépa thon', 'Prépa tzatziki', 'Prépa velouté',
].sort();
