// Master : update prix/unite + dedup pour toute la liste Foodflow.
// Règle : prix lu directement sur foodflow.fr, unite = suffixe (kg/L/pièce), quantite=1.
import 'dotenv/config';
import { db } from '../lib/firebase';
import { collection, getDocs, doc, updateDoc, deleteDoc } from 'firebase/firestore';

function norm(s: string) {
  return (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/\s+/g, ' ').trim();
}

const PRODUITS: { nom: string; prix: number; unite: string }[] = [
  // Boucherie
  { nom: 'Bourguignon UE ~4kg S/V', prix: 12.49, unite: 'kg' },
  { nom: 'Rôti de dinde cuit filet ±2,3kg', prix: 19.45, unite: 'kg' },
  { nom: 'Filet de poulet halal UE 2,5kg S/V', prix: 7.05, unite: 'kg' },
  { nom: 'Échine de porc français désossée ~2kg S/AT', prix: 6.25, unite: 'kg' },
  { nom: 'Steak haché Socopa rond 150g façon bouchère 15%MG VBF X8', prix: 15.88, unite: 'kg' },
  { nom: 'Paleron halal UE ~2,5kg S/V', prix: 13.57, unite: 'kg' },
  { nom: 'Cuisse de canard confite UE ~250g S/V X2', prix: 7.48, unite: 'pièce' },
  { nom: 'Paleron UE ~2,5kg S/V', prix: 13.57, unite: 'kg' },
  { nom: 'Filet de poulet français halal 2,5kg S/AT', prix: 8.98, unite: 'kg' },
  { nom: 'Steak haché Elivia rond 150g façon bouchère 15%MG VBF X8', prix: 15.83, unite: 'kg' },
  { nom: 'Palette de porc français sans os ~6kg S/AT', prix: 5.94, unite: 'kg' },
  { nom: 'Sauté de veau UE ~2kg S/V', prix: 16.84, unite: 'kg' },
  { nom: 'Confit de canard 6 cuisses S/V 1,5kg', prix: 19.11, unite: 'kg' },
  { nom: 'Steak haché Socopa rond 150g strié 15%MG VBF X8', prix: 15.96, unite: 'kg' },
  // Charcuterie
  { nom: 'Jambon Coupé 2KG env.', prix: 4.75, unite: 'kg' },
  { nom: 'Pastrami de boeuf français fumé cuit "Smocmeat" ~3kg non tranché', prix: 21.45, unite: 'kg' },
  { nom: 'Jambon cuit supérieur AC 10 tranches 450g', prix: 5.69, unite: 'pièce' },
  { nom: 'Plateau de charcuterie (jambon, coppa, rosette) 200g', prix: 3.95, unite: 'pièce' },
  { nom: 'Saucisse fumée à cuire supérieure ~120g X 15 S/AT', prix: 7.78, unite: 'kg' },
  { nom: 'Jambon sec supérieur tranché sans conservateurs 500 Gr', prix: 8.19, unite: 'pièce' },
  { nom: 'Jambon Serrano Tranché 500g', prix: 7.95, unite: 'pièce' },
  { nom: 'Saucisse de Toulouse ~160g x 8 S/V', prix: 11.50, unite: 'kg' },
  { nom: 'Fuet 160g', prix: 2.36, unite: 'pièce' },
  // Hygiène
  { nom: 'Bobine Essuie-tout 450 Feuilles x 6 Pc', prix: 9.69, unite: 'pièce' },
  { nom: 'Vinaigre Cristal x 1.5L', prix: 0.87, unite: 'pièce' },
  { nom: 'Spray nettoyant désinfectant cuisine 750 ml', prix: 4.20, unite: 'pièce' },
  { nom: 'Rouleau 20 sacs poubelle 70µ 130L', prix: 5.45, unite: 'pièce' },
  { nom: 'Nettoyant sol floor neutre 5L', prix: 9.50, unite: 'pièce' },
  { nom: 'Papier toilette 2 plis rouleau x 12', prix: 4.16, unite: 'pièce' },
  { nom: "Spray nettoyant multi-surfaces 5 en 1 - parfum clémentine/orange 750 mL", prix: 4.70, unite: 'pièce' },
  { nom: 'Liquide vaisselle écolabel 1L', prix: 3.90, unite: 'pièce' },
  { nom: 'Eponge inox 40g x 10', prix: 5.32, unite: 'pièce' },
  { nom: 'Éponge récurante verte x 10', prix: 7.32, unite: 'pièce' },
  { nom: 'Liquide lave-verre Orlav 5 L', prix: 19.26, unite: 'pièce' },
  { nom: 'Javel nature 2,6% 5L', prix: 2.31, unite: 'pièce' },
  { nom: 'Liquide vaisselle plonge citron 5L', prix: 6.06, unite: 'pièce' },
  { nom: 'Crème lavante mains parfum fleur de lin 5L', prix: 8.73, unite: 'pièce' },
  { nom: 'Gel nettoyant WC détartrant 750 ml', prix: 1.70, unite: 'pièce' },
  { nom: 'Spray désinfectant multi surfaces sans rinçage 750 mL', prix: 5.03, unite: 'pièce' },
  { nom: "Nettoyant multi-surfaces 5 en 1 L'Indispensable - clémentine/orange 5L", prix: 6.62, unite: 'pièce' },
  { nom: 'Lavettes microfibre 36x32 x 6', prix: 6.95, unite: 'pièce' },
  { nom: 'Rouleau 20 sacs poubelle 80µ 150L', prix: 8.45, unite: 'pièce' },
  { nom: 'Spray ultra détartrant 750 mL', prix: 5.03, unite: 'pièce' },
  { nom: 'Spray dégraissant multi-surface 750ml', prix: 6.95, unite: 'pièce' },
  // Crémerie
  { nom: 'Cheddar Tranché 1KG', prix: 9.45, unite: 'pièce' },
  { nom: 'Emmental Tranches 9x9 500g', prix: 10.06, unite: 'kg' },
  { nom: 'Camembert au lait Pasteurisé 200g', prix: 1.55, unite: 'pièce' },
  { nom: 'Mozzarella Pain 1KG', prix: 9.33, unite: 'kg' },
  { nom: 'Lait Entier UHT Valco Pack 6x1L', prix: 7.09, unite: 'pièce' },
  { nom: 'Feta Bloc 1kg', prix: 13.58, unite: 'kg' },
  { nom: 'Burrata 125g x16', prix: 11.98, unite: 'kg' },
  { nom: 'Brie Pasteurisé 3KG', prix: 7.39, unite: 'kg' },
  { nom: "Jaune d'Œuf 1L", prix: 9.15, unite: 'L' },
  { nom: 'Yaourt Grec 1 KG', prix: 4.77, unite: 'pièce' },
  { nom: 'Crème liquide 18% Baignes 6x1L', prix: 3.51, unite: 'L' },
  { nom: 'Oeuf plein air gros calibre x180', prix: 46.15, unite: 'pièce' },
  { nom: 'Crème Excellence Elle & Vire 35% 6x1L', prix: 5.89, unite: 'L' },
  { nom: 'Saint Nectaire Laitier 1.9KG env.', prix: 12.41, unite: 'kg' },
  { nom: 'Crème liquide 12% Baignes 6x1L', prix: 2.98, unite: 'L' },
  { nom: 'Oeuf plein air moyen x90', prix: 23.98, unite: 'pièce' },
  { nom: 'Crème liquide 35% Baignes 6x1L', prix: 4.86, unite: 'L' },
  { nom: 'Crème liquide 30% Baignes 6x1L', prix: 4.12, unite: 'L' },
  { nom: 'Camembert lait Cru 250Gr', prix: 3.44, unite: 'pièce' },
  { nom: 'Comté bloc 4 mois AOP 2-3KG', prix: 16.73, unite: 'kg' },
  { nom: 'Gouda 50 tranches 10x10cm 500g', prix: 14.85, unite: 'kg' },
  { nom: 'Parmesan Reggiano Bloc 1KG', prix: 19.77, unite: 'kg' },
  { nom: 'Crème fouettée à la vanille de Madagascar Isigny aérosol 500g', prix: 6.25, unite: 'pièce' },
  { nom: 'Chèvre Affiné Spécial Cuisson 20Gr X 24Pc', prix: 11.84, unite: 'pièce' },
  { nom: 'Chèvre frais Sous Vide 1KG', prix: 13.65, unite: 'pièce' },
  { nom: 'Œuf Entier 1L', prix: 4.38, unite: 'L' },
  { nom: 'Beurre extra fin origine France 1kg', prix: 9.50, unite: 'pièce' },
  { nom: 'Stracciatella 200g', prix: 3.08, unite: 'pièce' },
  { nom: 'Emmental Tranches 1KG', prix: 9.90, unite: 'kg' },
  { nom: 'Mascarpone Granarolo 500gr', prix: 3.96, unite: 'pièce' },
  { nom: 'Raclette nature tranchée 400g', prix: 5.08, unite: 'pièce' },
  { nom: 'Comté 18 mois 3KG', prix: 19.98, unite: 'kg' },
  { nom: "Jaune d'Œuf plein air 1L", prix: 10.94, unite: 'L' },
  { nom: 'Comté 6 mois 3KG', prix: 14.73, unite: 'kg' },
  { nom: 'Lait végétal avoine Alpro Barista 1Lx8', prix: 1.94, unite: 'L' },
  { nom: 'Beurre Micro 1/2 Sel 10gr X 100', prix: 12.41, unite: 'pièce' },
  { nom: 'Mini Camembert 150Gr', prix: 2.15, unite: 'pièce' },
  { nom: 'Lait végétal coco Alpro Barista 1Lx8', prix: 2.72, unite: 'L' },
  { nom: 'Lait végétal soja Alpro Barista 1Lx8', prix: 1.73, unite: 'L' },
  { nom: "ALT MLK BARISTA AVOINE 1Lx6 - Lait d'avoine végétal", prix: 1.99, unite: 'L' },
  { nom: "ALT MLK BARISTA AMANDE 1Lx6 - Lait d'amande végétal", prix: 2.30, unite: 'L' },
  { nom: 'ALT MLK BARISTA COCO 1Lx6 - Lait de coco végétal', prix: 2.30, unite: 'L' },
  { nom: 'Tomme Fraiche Aligot 1.8KG env.', prix: 10.36, unite: 'kg' },
  { nom: 'Raclette fumée tranchée 200g', prix: 5.92, unite: 'pièce' },
  { nom: 'Raclette nature tranchée 800g', prix: 9.90, unite: 'pièce' },
  { nom: 'Tomme Blanche 1,8KG env.', prix: 11.99, unite: 'kg' },
  { nom: 'Cheddar rouge pour burger 50 tranches 1kg', prix: 16.80, unite: 'kg' },
  { nom: "Blanc d'Œuf 1L", prix: 3.56, unite: 'L' },
  { nom: 'Brie 1kg', prix: 9.49, unite: 'pièce' },
  // Épicerie salée
  { nom: 'Saumon Fumé Norvège Tranché 1kg', prix: 29.85, unite: 'kg' },
  { nom: 'Ketchup Louis Martin 5kg', prix: 2.08, unite: 'kg' },
  { nom: 'Polpa Mutti 5/1', prix: 7.17, unite: 'pièce' },
  { nom: 'Cacahuètes grillées salées 1 KG', prix: 4.30, unite: 'pièce' },
  { nom: 'Olive noire dénoyautée 5/1', prix: 11.39, unite: 'pièce' },
  { nom: 'Farine T55 1kg x10', prix: 0.75, unite: 'kg' },
  { nom: 'Jus de veau Knorr Essentiel 750g', prix: 11.77, unite: 'pièce' },
  { nom: 'Huile GID 100% Tournesol X 5L', prix: 1.99, unite: 'L' },
  { nom: 'Vinaigre Framboise 50CL', prix: 3.55, unite: 'pièce' },
  { nom: "Moutarde à l'ancienne seau 1kg", prix: 3.08, unite: 'pièce' },
  { nom: 'Moutarde de Dijon 5kg', prix: 2.22, unite: 'kg' },
  { nom: 'Câpres Fines 4/4', prix: 4.01, unite: 'pièce' },
  { nom: 'Double concentré de tomate 4/4 0,88kg', prix: 2.89, unite: 'pièce' },
  { nom: 'Sel de mer fin seau 5kg', prix: 5.75, unite: 'pièce' },
  { nom: 'Thon Huile 4/4', prix: 6.70, unite: 'pièce' },
  { nom: 'Vinaigre de vin rouge 1L', prix: 1.35, unite: 'pièce' },
  { nom: 'Ail semoule sac 1kg', prix: 10.12, unite: 'kg' },
  { nom: 'Piment doux fumé (paprika fumé) tubo 450g', prix: 13.65, unite: 'pièce' },
  { nom: 'Riz Basmati 5kg', prix: 3.05, unite: 'kg' },
  { nom: "Huile d'Olive Vierge Extra X 1L", prix: 7.24, unite: 'L' },
  { nom: 'Huile 100% Tournesol X 1L', prix: 2.22, unite: 'L' },
  { nom: 'Curry Madras Moulu 500GR', prix: 4.45, unite: 'pièce' },
  { nom: 'Polenta express 1kg', prix: 3.95, unite: 'pièce' },
  { nom: 'Harissa Cap Bon 4/4', prix: 2.60, unite: 'pièce' },
  { nom: 'Olive noire dénoyautée 34/40 4/4 (0,85kg)', prix: 3.05, unite: 'pièce' },
  { nom: 'Pois chiches 4/4', prix: 1.78, unite: 'pièce' },
  { nom: 'Olives noires lamelles 3/1', prix: 7.82, unite: 'pièce' },
  { nom: 'Poivre noir moulu 500GR', prix: 6.79, unite: 'pièce' },
  { nom: 'Harissa Cap Bon tube 70g', prix: 0.77, unite: 'pièce' },
  { nom: 'Sauce Worcestershire Heinz 150 ML', prix: 2.99, unite: 'pièce' },
  { nom: 'Tabasco rouge 60 ML', prix: 3.49, unite: 'pièce' },
  { nom: 'Origan 500GR', prix: 9.94, unite: 'pièce' },
  { nom: 'Poivre noir moulu 1kg', prix: 14.60, unite: 'pièce' },
  { nom: 'Huile arôme truffe blanche 250ml', prix: 7.65, unite: 'pièce' },
  { nom: 'Mix tandoori 450g', prix: 8.99, unite: 'pièce' },
  { nom: 'Cannelle Moulue 450GR', prix: 7.55, unite: 'pièce' },
  { nom: 'Double concentré de tomates Louis Martin 4/4 0,88kg', prix: 3.79, unite: 'pièce' },
  { nom: 'Poivre noir concassé 500GR', prix: 9.99, unite: 'pièce' },
  { nom: 'Riz Rond 5 KG', prix: 2.18, unite: 'kg' },
  { nom: 'Mélange 5 baies 1KG', prix: 20.70, unite: 'pièce' },
  { nom: 'Gingembre Moulu 500GR', prix: 6.49, unite: 'pièce' },
  { nom: 'Clous de girofle 50g', prix: 2.89, unite: 'pièce' },
  { nom: 'Curry de Madras tubo 330ml 125g', prix: 3.85, unite: 'pièce' },
  { nom: 'Sauce Tomate Tabana 5/1', prix: 7.95, unite: 'pièce' },
  { nom: 'Riz Basmati Bio 5kg', prix: 3.79, unite: 'kg' },
  // Légumes
  { nom: 'Mélange de jeunes pousses thermo 1kg', prix: 6.78, unite: 'kg' },
  { nom: 'Concombre pièce ~300g', prix: 0.86, unite: 'pièce' },
  { nom: 'Tomate rouge ronde N°3', prix: 3.15, unite: 'kg' },
  { nom: 'Pdt GT lavée', prix: 1.25, unite: 'kg' },
  { nom: 'Oignon jaune', prix: 0.67, unite: 'kg' },
  { nom: 'Oignon rouge', prix: 1.20, unite: 'kg' },
  { nom: 'Basilic botte', prix: 0.65, unite: 'pièce' },
  { nom: 'Cebette botte', prix: 0.99, unite: 'pièce' },
  { nom: 'Coriandre botte', prix: 0.59, unite: 'pièce' },
  { nom: 'Menthe botte', prix: 0.52, unite: 'pièce' },
  { nom: 'Persil plat botte', prix: 0.59, unite: 'pièce' },
  { nom: 'Carotte 40+ lavée', prix: 0.98, unite: 'kg' },
  { nom: 'Chou rouge ~1,3kg pièce', prix: 1.29, unite: 'kg' },
  { nom: 'Courgette verte cal. 14/21', prix: 2.11, unite: 'kg' },
  { nom: 'Aubergine', prix: 2.52, unite: 'kg' },
  { nom: 'Champignon de Paris *pied coupé* blanc 3kg', prix: 3.56, unite: 'kg' },
  { nom: 'Ail pelée 1KG', prix: 6.87, unite: 'pièce' },
  { nom: 'Poivron rouge', prix: 2.97, unite: 'kg' },
  { nom: 'Romarin botte', prix: 0.80, unite: 'pièce' },
  { nom: 'Champignon Portobello 2kg', prix: 5.99, unite: 'kg' },
  { nom: 'Potimarron ~1,6kg pièce', prix: 2.75, unite: 'kg' },
  { nom: 'Échalote longue', prix: 2.85, unite: 'kg' },
  { nom: 'Betterave Crue', prix: 3.00, unite: 'kg' },
  { nom: 'Piment Rouge', prix: 6.85, unite: 'kg' },
  { nom: 'Poivron jaune', prix: 2.92, unite: 'kg' },
  { nom: 'Poivron vert', prix: 2.53, unite: 'kg' },
  { nom: 'Tomate Cerise Multicolore', prix: 6.08, unite: 'kg' },
  { nom: 'Salade Iceberg', prix: 1.40, unite: 'pièce' },
  { nom: 'Aneth botte', prix: 0.68, unite: 'pièce' },
  { nom: 'Avocat Hass cal 22', prix: 0.94, unite: 'pièce' },
  { nom: 'Avocat Hass cal 18', prix: 1.35, unite: 'pièce' },
  { nom: 'Patate douce', prix: 1.74, unite: 'kg' },
  { nom: 'Butternut ~1,6kg pièce', prix: 1.43, unite: 'kg' },
  { nom: 'Panais', prix: 1.99, unite: 'kg' },
  { nom: 'Ciboulette botte', prix: 0.59, unite: 'pièce' },
  { nom: 'Tomate à farcir (N°2)', prix: 4.70, unite: 'kg' },
  { nom: 'Mesclun thermo 1kg', prix: 7.75, unite: 'kg' },
  { nom: 'Tomate Roma', prix: 4.52, unite: 'kg' },
  // Équipements
  { nom: 'Pique en bambou "golf" 15cm x200', prix: 3.55, unite: 'pièce' },
  { nom: 'Cartouche de gaz pour chalumeau 360ml', prix: 7.61, unite: 'pièce' },
  { nom: 'Papier Aluminium 0,29 x 200 m', prix: 13.88, unite: 'pièce' },
  { nom: 'Film Alimentaire 0,30 x 300 m', prix: 8.07, unite: 'pièce' },
  { nom: 'Gobelet 10cL carton brun x50', prix: 1.54, unite: 'pièce' },
  { nom: 'Bloc maitre hotel 8 x 15 cm x10', prix: 14.70, unite: 'pièce' },
  { nom: 'Kit 3/1 (fourchette, couteau, serviette 1 pli) x250', prix: 20.01, unite: 'pièce' },
  { nom: 'Boîte burger kraft brun 120x116x70 x100', prix: 16.96, unite: 'pièce' },
  { nom: 'Gant Jetable Vinyl T9/L x 100 Pc', prix: 3.95, unite: 'pièce' },
  { nom: 'Pot salade 780mL carton kraft brun PP x50', prix: 4.53, unite: 'pièce' },
  { nom: 'Couvercle pot salade 780mL PP x50', prix: 4.39, unite: 'pièce' },
  { nom: '50 serviettes blanches double point tissue 40x40cm pliée en 8', prix: 2.03, unite: 'pièce' },
  { nom: 'Étiquette traçabilité 100x40mm post-it x300', prix: 18.90, unite: 'pièce' },
  { nom: 'Colis de 50 bobines thermiques CB 57x40x12mm 18m', prix: 17.50, unite: 'pièce' },
  { nom: 'Pot salade 1100mL carton kraft brun PP x50', prix: 5.66, unite: 'pièce' },
  { nom: 'Couvercle pot salade 1100mL PP x50', prix: 5.75, unite: 'pièce' },
  { nom: 'Barquette alu 350mL x100', prix: 8.49, unite: 'pièce' },
  { nom: 'Gant Jetable Latex L x 100 Pc', prix: 5.80, unite: 'pièce' },
  { nom: 'Colis de 30 bobines thermiques Caisse Enr. 80x80x12mm 75m', prix: 49.90, unite: 'pièce' },
  { nom: 'Poche patissiere jetable 27x50cm x100', prix: 12.86, unite: 'pièce' },
  { nom: 'Gant nitrile noir L x100', prix: 4.13, unite: 'pièce' },
  { nom: 'Nappe papier blanche 30x40cm x 500', prix: 16.13, unite: 'pièce' },
  { nom: 'Agitateurs café bambou 12cm x1000', prix: 4.95, unite: 'pièce' },
  { nom: 'Torchon usage professionnel 50x70cm X12', prix: 15.25, unite: 'pièce' },
  { nom: 'Tablier coton bleu - la pièce', prix: 13.49, unite: 'pièce' },
  { nom: 'Sac kraft sans poignée (29,5x19x12 cm) X250', prix: 59.87, unite: 'pièce' },
  { nom: 'Calot papier frange rouge x 100', prix: 7.30, unite: 'pièce' },
  { nom: 'Gobelet 17cL carton brun x50', prix: 2.02, unite: 'pièce' },
  { nom: 'Essuie-mains 200 feuilles 19,5x23cm x20', prix: 30.63, unite: 'pièce' },
  { nom: 'Gobelet 24cL carton brun x50', prix: 1.64, unite: 'pièce' },
  { nom: 'Pique en bambou "golf" 9cm x100', prix: 3.25, unite: 'pièce' },
  { nom: 'Assiette 180mm diamètre carton brun × 50', prix: 3.75, unite: 'pièce' },
  { nom: 'Assiette 230mm diamètre carton brun × 50', prix: 3.85, unite: 'pièce' },
  { nom: 'Fourchette bambou 17cm X50', prix: 5.79, unite: 'pièce' },
  { nom: 'Couteau bambou 17cm X50', prix: 6.45, unite: 'pièce' },
  { nom: 'Cuillère bambou 17cm X50', prix: 6.20, unite: 'pièce' },
  { nom: 'Cure-dents X1000 Pc', prix: 1.34, unite: 'pièce' },
  { nom: 'Couvercle gobelet 24cL carton x50', prix: 1.95, unite: 'pièce' },
  // Épicerie sucrée
  { nom: 'Pack sucre semoule 10X1kg', prix: 1.34, unite: 'kg' },
  { nom: 'Sucre cassonade 1kg', prix: 2.52, unite: 'kg' },
  { nom: 'Chocolat pistol noir Barry 50% 5kg', prix: 64.96, unite: 'pièce' },
  { nom: 'Amandes Poudre 1KG', prix: 10.38, unite: 'pièce' },
  { nom: 'Arôme Vanille 1L', prix: 7.75, unite: 'pièce' },
  { nom: 'Spéculoos Concassé 1.1kg', prix: 6.25, unite: 'pièce' },
  { nom: 'Noisette hachée grillée 1kg', prix: 16.46, unite: 'pièce' },
  { nom: 'Praliné amandes noisettes 50% seau 1kg', prix: 19.91, unite: 'kg' },
  { nom: 'Pignons de Pin 1KG', prix: 30.99, unite: 'pièce' },
  { nom: 'Nutella 1kg', prix: 7.85, unite: 'pièce' },
  { nom: 'Miel squeez 500GR', prix: 6.15, unite: 'pièce' },
  { nom: 'Tahine (crème de sésame) seau 3kg', prix: 18.80, unite: 'pièce' },
  { nom: "Pâte d'arachide 4/4", prix: 6.97, unite: 'pièce' },
  { nom: 'Cerneaux de Noix 1KG', prix: 8.61, unite: 'pièce' },
  { nom: 'Thé blanc bai mu dan BIO x15 sachets', prix: 6.97, unite: 'pièce' },
  { nom: 'Thé noir Earl Grey arôme naturel de bergamote BIO x15 sachets', prix: 6.10, unite: 'pièce' },
  { nom: 'Thé vert à la menthe BIO x15 sachets', prix: 6.97, unite: 'pièce' },
  { nom: 'Thé vert arôme naturel de jasmin BIO x15 sachets', prix: 6.10, unite: 'pièce' },
  { nom: 'Matcha 1kg - Grade premium', prix: 98.00, unite: 'kg' },
  { nom: 'Chicorée nature', prix: 5.68, unite: 'pièce' },
  { nom: 'Chaï Latte BIO 1kg : Spicy & Delicious', prix: 29.00, unite: 'kg' },
  { nom: 'Chocolat pistol noir 55% 5kg', prix: 78.90, unite: 'pièce' },
  { nom: 'Instantanée - CHERICO "CHICOREE NATURE" 250G', prix: 17.78, unite: 'pièce' },
  { nom: 'Thé vert au gingembre et citron BIO x15 sachets', prix: 6.91, unite: 'pièce' },
  { nom: 'Golden latte Monbana 350g', prix: 12.53, unite: 'pièce' },
  { nom: 'Sucre glace 1kg', prix: 2.84, unite: 'kg' },
  { nom: 'Colorant alimentaire rouge 50ml', prix: 2.43, unite: 'pièce' },
  // La Cave
  { nom: 'Cubi Vin Rouge 10 L', prix: 16.02, unite: 'pièce' },
  { nom: 'Le Rouge - Les Essentiels x Domaine Isle Saint Pierre 12,5%vol 75cl', prix: 6.00, unite: 'pièce' },
  { nom: 'Le Rouge - Les Essentiels x Domaine Isle Saint Pierre 12,5%vol Bib 5L', prix: 16.79, unite: 'pièce' },
  { nom: 'Le Blanc - Les Essentiels x Domaine Isle Saint-Pierre 12,5%vol 75cl', prix: 6.00, unite: 'pièce' },
  { nom: "Merlot rouge IGP Pays d'Oc fontaine 10L", prix: 22.09, unite: 'pièce' },
  { nom: 'Viognier 75cl', prix: 6.65, unite: 'pièce' },
  { nom: 'Marsanne 75cl', prix: 5.15, unite: 'pièce' },
  { nom: "Colombelle l'Original IGP Côtes de Gascogne blanc 75cl", prix: 4.14, unite: 'pièce' },
  { nom: 'Velodoro Prosecco DOC extra dry 75cl', prix: 4.39, unite: 'pièce' },
  // Spiritueux
  { nom: "Crème (de whisky) Irlandaise Bailey's 17% 1L", prix: 18.45, unite: 'pièce' },
  { nom: 'Vodka Poliakov 37,5% 70cl', prix: 9.42, unite: 'pièce' },
  { nom: "Gin Gibson's 37,5% 70cl", prix: 9.38, unite: 'pièce' },
  { nom: "Gin Gordon's 37,5% 70cl", prix: 11.38, unite: 'pièce' },
  { nom: 'Martini Bianco 14,5% 1L', prix: 9.70, unite: 'pièce' },
  { nom: 'Crème de cassis 18% 1L', prix: 8.97, unite: 'L' },
  { nom: 'Whisky Ballantines 40% 70cl', prix: 13.36, unite: 'pièce' },
  { nom: 'Rhum blanc agricol St James 40% 70cl', prix: 9.30, unite: 'pièce' },
  { nom: 'Ricard 45% 1L', prix: 16.89, unite: 'pièce' },
  { nom: 'Pastis 51 45% 1L', prix: 21.00, unite: 'pièce' },
  { nom: 'Limoncello 25% 70cl', prix: 8.79, unite: 'pièce' },
  { nom: 'Picon Bière 18% 1L', prix: 9.89, unite: 'pièce' },
  { nom: 'Crème de pêche 18% 1L', prix: 8.49, unite: 'L' },
  { nom: 'Crème de mûre 18% 1L', prix: 10.49, unite: 'pièce' },
  { nom: 'Aperol 12,5% 70cl', prix: 10.56, unite: 'pièce' },
  { nom: 'Get 27 17,9% 70cl', prix: 11.74, unite: 'pièce' },
  // Boissons
  { nom: 'Perrier 1L x6', prix: 5.16, unite: 'pièce' },
  { nom: 'Sirop de grenadine 1L', prix: 2.86, unite: 'pièce' },
  { nom: "Jus d'orange Granini 1L X6", prix: 22.99, unite: 'pièce' },
  { nom: 'CIAO KOMBUCHA saveur gingembre hibiscus 330mlx6', prix: 13.44, unite: 'pièce' },
  { nom: 'Limonade arôme naturel citron 1,5L', prix: 1.33, unite: 'pièce' },
  { nom: 'Schweppes Indian Tonic 1,5L', prix: 2.32, unite: 'pièce' },
  // Surgelé
  { nom: 'Chute de saumon fumé 1kg', prix: 12.24, unite: 'pièce' },
  { nom: 'Framboise 1kg', prix: 10.69, unite: 'kg' },
  { nom: 'Myrtille 1kg', prix: 10.69, unite: 'kg' },
];

async function main() {
  console.log(`${PRODUITS.length} produits à traiter\n`);
  const pfSnap = await getDocs(collection(db, 'produitsFournisseurs'));
  const all = pfSnap.docs.map(d => ({ id: d.id, ...(d.data() as any) }));

  let okCount = 0, missCount = 0, dupCount = 0;
  const missing: string[] = [];

  for (const p of PRODUITS) {
    const matches = all.filter(x => x.fournisseur === 'Foodflow' && norm(x.nom) === norm(p.nom));
    if (matches.length === 0) {
      missing.push(p.nom);
      missCount++;
      continue;
    }
    const toKeep = matches.find(m => m.foodflowCode) || matches[0];
    await updateDoc(doc(db, 'produitsFournisseurs', toKeep.id), {
      prix: p.prix, unite: p.unite, quantite: 1, updatedAt: new Date().toISOString(),
    });
    okCount++;
    console.log(`✓ ${toKeep.foodflowCode || '—'} | ${p.prix} €/${p.unite} | ${p.nom}`);

    for (const m of matches) {
      if (m.id === toKeep.id) continue;
      await deleteDoc(doc(db, 'produitsFournisseurs', m.id));
      dupCount++;
    }
  }

  console.log(`\n────────────────────`);
  console.log(`✓ ${okCount} mis à jour`);
  console.log(`✗ ${dupCount} doublons supprimés`);
  console.log(`? ${missCount} introuvables`);
  if (missing.length) {
    console.log('\nIntrouvables :');
    for (const m of missing) console.log(`  - ${m}`);
  }
}
main().catch(e => { console.error(e); process.exit(1); });
